# Generated by Django 5.1.2 on 2024-11-06 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BonCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_bon_commande', models.CharField(max_length=20)),
                ('date_commande', models.DateTimeField(auto_now_add=True)),
                ('prix_total', models.FloatField(null=True)),
            ],
        ),
    ]
