# Generated by Django 5.1.2 on 2024-11-06 09:47

import django.db.models.deletion
import produit.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categorie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_produit', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('qte_stock', models.IntegerField()),
                ('prix', models.FloatField()),
                ('image_url', models.ImageField(blank=True, null=True, upload_to=produit.models.upload_to)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categorie.categorie')),
            ],
        ),
    ]
